const languageOptions = {
  lang: {
    rangeSelectorZoom: "Зум:",
    rangeSelectorFrom: "От:",
    rangeSelectorTo: "До:",
    downloadPNG: "Скачать в PNG",
    downloadJPEG: "Скачать в JPEG",
    downloadPDF: "Скачать в PDF",
    downloadSVG: "Скачать в SVG",
    exportButtonTitle: "Экспорт в растровый или векторный формат",
    printButtonTitle: "Распечатать график",
    loading: "Загрузка...",
    months: [
      "января",
      "февраля",
      "марта",
      "апреля",
      "мая",
      "июня",
      "июля",
      "августа",
      "сентября",
      "октября",
      "ноября",
      "декабря",
    ],
    shortMonths: [
      "янв.",
      "фев.",
      "мар.",
      "апр.",
      "мая",
      "июн.",
      "июл.",
      "авг.",
      "сен.",
      "окт.",
      "ноя.",
      "дек.",
    ],
    weekdays: [
      "воскресенье",
      "понедельник",
      "вторник",
      "среда",
      "четверг",
      "пятница",
      "суббота",
    ],
    decimalPoint: ".",
    resetZoom: "Сбросить масштаб",
    resetZoomTitle: "Сбросить зум к 1:1",
    thousandsSep: ".",
  },
};

export default languageOptions;
